### ISSUE TITLE
Typo in Settings 

### ISSUE THREAD

**Issue by ghost** [bitpopulous/PopEx#39]
Typo in 'Settings' screen: '_Device managemet_' should be '_Device manageme**n**t_'
![Typo](https://user-images.githubusercontent.com/85500271/121027199-10305180-c7a7-11eb-91ae-1347bf00bd1f.png)

**Comment by tomsarega** [comment]
This issue should be closed

**Comment by ghost** [comment]
Fixed! Issue closed.
